#include "uiopenglmaterial_diffusebumpmapshaders.cxx"
#include "uiopenglmaterial_sbmapshaders.cxx"
#include "uiopenglmaterial_singlecolorshaders.cxx"
#include "uiopenglmaterial_singletextureshaders.cxx"
#include "uiopenglmaterial_textureandlightmapshaders.cxx"
#include "uiopenglmaterials.cxx"
